/**
 * scripts/provision-users.ts
 *
 * Pre-provisions the real account(s) listed in `public.allowed_emails` via the GoTrue Admin API,
 * since public email/password signup is disabled (supabase/config.toml, [auth.email]
 * enable_signup = false) — this is how the six real accounts get their email/password identity.
 *
 * IMPORTANT: the before_user_created auth hook does NOT gate this path. Verified empirically
 * (2026-09-16): an admin.createUser() call for a deliberately non-allowlisted test address
 * (outsider-test-DELETE-ME@vg-eval-test.invalid, created then immediately deleted) succeeded
 * without the hook rejecting it. This makes sense — the hook gates public-facing signup/OAuth
 * endpoints, not trusted service-role admin operations — but it means THIS script is the actual
 * safety boundary for its own path, not the hook. It re-checks `allowed_emails` itself before
 * calling admin.createUser, as defense-in-depth, even though its only real input is
 * `allowed_emails` in the first place. The hook's real job — and the one AC-AUTH-05 actually
 * tests — is the Google OAuth path, which genuinely is public-facing and untested until someone
 * completes a real Google sign-in with an outsider account (can't be automated from here).
 *
 * Idempotent: an email that already has an auth.users row is left alone (password NOT
 * regenerated — the whole point of recording it once is that it stays valid). Passwords are
 * written to docs/CREDENTIALS.local.md (gitignored, never commit — shared only via the
 * submission email per the brief's "How to submit").
 *
 * Usage: npx tsx scripts/provision-users.ts   (reads SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY
 * from .env.local)
 */
import { createClient } from "@supabase/supabase-js";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const ENV_LOCAL_PATH = join(REPO_ROOT, ".env.local");
const CREDENTIALS_PATH = join(REPO_ROOT, "docs", "CREDENTIALS.local.md");
// Machine-readable twin of the table above, read by tests/integration/auth.test.ts. Same
// gitignore rule (docs/CREDENTIALS.local.*) covers both.
const CREDENTIALS_JSON_PATH = join(REPO_ROOT, "docs", "CREDENTIALS.local.json");

interface CredentialEntry {
  email: string;
  password: string;
  brand: string;
  role: string;
}

function loadEnvLocal(): Record<string, string> {
  const text = readFileSync(ENV_LOCAL_PATH, "utf-8");
  const env: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const m = /^([A-Z_]+)=(.*)$/.exec(line.trim());
    if (m) env[m[1]!] = m[2]!;
  }
  return env;
}

function generatePassword(): string {
  // 24 random bytes, base64url — well above minimum_password_length, no ambiguity about
  // character-class requirements since config.toml leaves password_requirements unset.
  return randomBytes(24).toString("base64url");
}

async function main(): Promise<void> {
  const env = loadEnvLocal();
  const url = env.SUPABASE_URL;
  const serviceKey = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    throw new Error(".env.local is missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  }

  const admin = createClient(url, serviceKey);

  const { data: allowed, error: allowedErr } = await admin
    .from("allowed_emails")
    .select("email, brand_id, role, brands:brand_id(slug)");
  if (allowedErr) throw new Error(`Could not read allowed_emails: ${allowedErr.message}`);
  if (!allowed || allowed.length === 0) {
    console.log("allowed_emails is empty — nothing to provision.");
    return;
  }

  const { data: existingList, error: listErr } = await admin.auth.admin.listUsers();
  if (listErr) throw new Error(`Could not list existing users: ${listErr.message}`);
  const existingEmails = new Set(existingList.users.map((u) => u.email?.toLowerCase()));

  if (!existsSync(CREDENTIALS_PATH)) {
    writeFileSync(
      CREDENTIALS_PATH,
      "# Generated credentials — gitignored, never commit\n\n" +
        "Generated by `scripts/provision-users.ts`. Share only via the submission email, per the\n" +
        "brief's \"How to submit\" — not by committing this file (it's gitignored on purpose).\n\n" +
        "| Email | Password | Brand | Role |\n|---|---|---|---|\n",
      "utf-8",
    );
  }
  const existingJson: CredentialEntry[] = existsSync(CREDENTIALS_JSON_PATH)
    ? (JSON.parse(readFileSync(CREDENTIALS_JSON_PATH, "utf-8")) as CredentialEntry[])
    : [];

  let created = 0;
  let skipped = 0;

  for (const row of allowed) {
    const email = row.email as string;
    const brandSlug = (row as unknown as { brands: { slug: string } }).brands?.slug ?? "?";
    const role = row.role as string;

    if (existingEmails.has(email.toLowerCase())) {
      console.log(`skip (already exists): ${email}`);
      skipped++;
      continue;
    }

    const password = generatePassword();
    const { data: createdUser, error: createErr } = await admin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
    });
    if (createErr) {
      console.error(`FAILED to create ${email}: ${createErr.message}`);
      continue;
    }
    console.log(`created: ${email} (${brandSlug}/${role}) — id ${createdUser.user.id}`);
    appendFileSync(CREDENTIALS_PATH, `| ${email} | ${password} | ${brandSlug} | ${role} |\n`, "utf-8");
    existingJson.push({ email, password, brand: brandSlug, role });
    created++;
  }

  writeFileSync(CREDENTIALS_JSON_PATH, JSON.stringify(existingJson, null, 2), "utf-8");

  console.log(`\nDone. Created ${created}, skipped ${skipped} (already existed).`);
  if (created > 0) {
    console.log(`New passwords written to ${CREDENTIALS_PATH} and ${CREDENTIALS_JSON_PATH} (both gitignored).`);
  }

  // Verify the membership trigger actually fired for everyone provisioned this run or before.
  const { data: memberships, error: memErr } = await admin
    .from("memberships")
    .select("user_id, role, brands:brand_id(slug)");
  if (memErr) throw new Error(`Could not verify memberships: ${memErr.message}`);
  console.log(`\nmemberships table now has ${memberships?.length ?? 0} row(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
