/**
 * scripts/sync-domain-to-edge-functions.ts
 *
 * Deno (Supabase Edge Functions) does not resolve Node/NodeNext-style ".js" import specifiers
 * against sibling ".ts" files — verified by deploying a real test function that imported
 * packages/domain directly: the bundler failed with "Module not found ... types.js", even though
 * only types.ts exists. This is a real, load-bearing constraint, not a style preference.
 *
 * packages/domain/src stays the single source of truth (Node/Vite/Vitest all resolve its ".js"
 * specifiers correctly via NodeNext). This script produces a byte-for-byte mirror under
 * supabase/functions/_shared/domain/ with only the import specifiers rewritten (".js" -> ".ts"),
 * so Edge Functions import from there instead of maintaining a hand-written, driftable copy.
 *
 * Run before every `supabase functions deploy` that touches an import-pipeline function:
 *   npm run sync:domain
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const SRC_DIR = join(REPO_ROOT, "packages", "domain", "src");
const DEST_DIR = join(REPO_ROOT, "supabase", "functions", "_shared", "domain");

function listTsFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...listTsFiles(full));
    } else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) {
      out.push(full);
    }
  }
  return out;
}

function main(): void {
  rmSync(DEST_DIR, { recursive: true, force: true });
  mkdirSync(DEST_DIR, { recursive: true });

  const files = listTsFiles(SRC_DIR);
  let count = 0;
  for (const srcPath of files) {
    const rel = relative(SRC_DIR, srcPath);
    const destPath = join(DEST_DIR, rel);
    mkdirSync(dirname(destPath), { recursive: true });

    let content = readFileSync(srcPath, "utf-8");
    // Only rewrite relative-import specifiers ("./x.js", "../x.js"), never bare package names.
    content = content.replace(/from\s+["'](\.[^"']+)\.js["']/g, 'from "$1.ts"');
    content =
      `// AUTO-GENERATED by scripts/sync-domain-to-edge-functions.ts from packages/domain/src/${rel.replace(/\\/g, "/")} — do not hand-edit, re-run the sync script instead.\n` +
      content;

    writeFileSync(destPath, content, "utf-8");
    count++;
  }

  console.log(`Synced ${count} file(s) from packages/domain/src to supabase/functions/_shared/domain.`);
}

main();
